btt/views.py
"""Module that handles web views."""
from flask import (
    render_template,
    url_for,
    redirect,
    session,
    Blueprint,
    flash,
    request,
)
from flask_login import login_required, current_user
from sqlalchemy.orm.exc import NoResultFound
from .database import Transaction, Account, Category
from .forms import (
    ModifyTransactionForm,
    AddTransactionForm,
    SearchTransactionsForm,
    UploadTransactionsForm,
    AddAccountForm,
    ModifyAccountForm,
    ModifyCategoryForm,
    AddCategoryForm,
    ProcessUploadedTransactionsForm,
    ClassifyTransactionColumnsForm,
    ClassifyTransactionRowsForm,
    ReportForm,
)
from .classification import predict_categories, predict_columns
from werkzeug.utils import secure_filename
from .database import db
from .reports import graph
from tempfile import mkdtemp
import datetime
import csv
import os


web = Blueprint("web", __name__)


@web.route("/")
@web.route("/home")
def home_page():
    """Return Home HTML page."""
    return render_template(
        "home.html", login_time=session.get("login_time"), menu="home"
    )


@web.route("/accounts")
@login_required
def accounts_page():
    """Return Accounts HTML page."""
    # for membership in current_user.memberships:
    #     if membership.active:
    #         accounts = membership.group.accounts
    accounts = current_user.group().accounts
    known_accounts = [
        account for account in accounts if account.accname != "Unknown"
    ]
    return render_template(
        "accounts.html", accounts=known_accounts, menu="accounts"
    )


@web.route("/accounts/modify/<int:accno>/", methods=["GET", "POST"])
@login_required
def modify_account(accno):
    """
    Modify or delete accounts.

    Return a form for modifying accounts or process submitted
    form and redirect to Accounts HTML page.
    """
    group = current_user.group()
    try:
        account = Account.query.filter_by(group=group, accno=accno).one()
    except NoResultFound:
        flash("Invalid account.")
        return redirect(url_for(".accounts_page"))
    accounts = current_user.group().accounts
    form = ModifyAccountForm()
    form.account_name.default = account.accname

    if form.validate_on_submit():
        if form.modify.data:
            for item in accounts:
                if (
                    item.accname == form.account_name.data
                    and item.accname != form.account_name.default
                ):
                    flash("Another account already has this name.")
                    return redirect(url_for(".modify_account", accno=accno))
            account.accname = form.account_name.data
            db.session.add(account)
            db.session.commit()
        elif form.delete.data:
            for transaction in current_user.group().transactions:
                if transaction.account == account:
                    unknown_account = Account.query.filter_by(
                        group=current_user.group(), accname="Unknown"
                    ).one()
                    transaction.account = unknown_account
                    db.session.add(transaction)
                    db.session.commit()
            db.session.delete(account)
            db.session.commit()
        return redirect(url_for(".accounts_page"))

    form.process()  # Do this after validate_on_submit or breaks CSRF token

    return render_template(
        "modify_account.html", form=form, accno=accno, menu="accounts"
    )


@web.route("/accounts/add", methods=["GET", "POST"])
@login_required
def add_account():
    """
    Add a transaction.

    Return a form for adding an account or process submitted
    form and redirect to Accounts HTML page.
    """
    accounts = current_user.group().accounts

    form = AddAccountForm()
    form.account_name.default = "New Account"

    if form.validate_on_submit():
        if form.add.data:
            for account in accounts:
                if account.accname == form.account_name.data:
                    flash("Account already exists.")
                    return redirect(url_for(".add_account"))
            account = Account()
            account.accname = form.account_name.data
            account.group = current_user.group()
            db.session.add(account)
            db.session.commit()
        return redirect(url_for(".accounts_page"))

    form.process()  # Do this after validate_on_submit or breaks CSRF token

    return render_template("add_account.html", form=form, menu="accounts")


@web.route("/transactions")
@login_required
def transactions_page():
    """Return Transactions HTML page."""
    transaction_numbers = session.get("transactions", (-1,))
    transactions = [
        transaction
        for transaction in current_user.group().transactions
        if transaction.transno in transaction_numbers
    ]
    return render_template(
        "transactions.html", transactions=transactions, menu="transactions"
    )


@web.route("/transactions/delete/<int:transno>/")
@login_required
def delete_transaction(transno):
    """Delete transaction."""
    group = current_user.group()
    try:
        transaction_to_delete = Transaction.query.filter_by(
            group=group, transno=transno
        ).one()
    except NoResultFound:
        flash("Invalid transaction.")
        return redirect(url_for(".transactions_page"))
    db.session.delete(transaction_to_delete)
    db.session.commit()
    flash("Transaction deleted.")
    if transno in session.get("transactions", (-1,)):
        session["transactions"].remove(transno)
    return redirect(url_for(".transactions_page"))


@web.route("/transactions/search", methods=["GET", "POST"])
@login_required
def search_transactions():
    """
    Search for transactions.

    Return a form for searching transactions or process submitted
    form and render Transactions HTML page.
    """
    categories = current_user.group().categories
    category_types = sorted({category.cattype for category in categories})
    accounts = current_user.group().accounts

    form = SearchTransactionsForm()

    # Form choices and defaults
    if current_user.group().transactions:
        form.start_date.default = current_user.group().transactions[0].date
    else:
        form.start_date.default = datetime.datetime.now()
    form.end_date.default = datetime.datetime.now()
    form.category_names.choices = [
        (category.catname, category.catname) for category in categories
    ]
    form.category_names.default = [category.catname for category in categories]
    form.category_types.choices = [
        (category_type, category_type) for category_type in category_types
    ]
    form.category_types.default = [
        category_type for category_type in category_types
    ]
    form.account_names.choices = [
        (account.accname, account.accname) for account in accounts
    ]
    form.account_names.default = [account.accname for account in accounts]

    if form.validate_on_submit():
        # This must go here or else before_app_request will try to commit
        # transaction with NULL fields when SQLALCHEMY_COMMIT_ON_TEARDOWN
        # is set to True
        if form.search.data:
            start_date = form.start_date.data
            end_date = form.end_date.data
            category_names = form.category_names.data
            category_types = form.category_types.data
            account_names = form.account_names.data
            description = form.description.data
            if description:
                description = description.lower()
            transactions = current_user.group().transactions
            selected_transactions = []
            for transaction in transactions:
                trans_description = transaction.description.lower()
                if description and description not in trans_description:
                    continue
                if (
                    transaction.date >= start_date
                    and transaction.date <= end_date
                    and transaction.category.catname in category_names
                    and transaction.category.cattype in category_types
                    and transaction.account.accname in account_names
                ):
                    selected_transactions.append(transaction)
        elif form.cancel.data:
            selected_transactions = current_user.group().transactions

        session["transactions"] = [
            transaction.transno for transaction in selected_transactions
        ]

        return redirect(url_for(".transactions_page"))

    form.process()  # Do this after validate_on_submit or breaks CSRF token

    return render_template(
        "search_transactions.html", form=form, menu="transactions"
    )


@web.route("/transactions/add", methods=["GET", "POST"])
@login_required
def add_transaction():
    """
    Add a transaction.

    Return a form for adding a transaction or process submitted
    form and redirect to Transactions HTML page.
    """
    categories = current_user.group().categories
    accounts = current_user.group().accounts

    category_names = [
        (category.catname, category.catname) for category in categories
    ]
    account_names = [
        (account.accname, account.accname) for account in accounts
    ]

    form = AddTransactionForm()
    form.date.default = datetime.datetime.now()
    form.description.default = ""
    form.category_name.choices = category_names
    form.category_name.default = category_names[0]
    form.account_name.choices = account_names
    form.account_name.default = account_names[0]
    form.amount.default = "{:.2f}".format(0)
    form.description.default = "Description"

    if form.validate_on_submit():
        # This must go here or else before_app_request will try to commit
        # transaction with NULL fields when SQLALCHEMY_COMMIT_ON_TEARDOWN
        # is set to True
        transaction = Transaction(group=current_user.group())

btt/templates/accounts.html
{% extends "base.html" %}

{% block title %}BTT{% endblock %}

{% block page_content %}

<h2>Accounts:</h2>
<div class="row">
<div class="col-md-4">
<table class="table table-striped table-bordered table-hover">
    <tr>
        <th>Account Name</th>
        <th>Action</th>
    </tr>

   {% for account in accounts %}

   <tr>
       <td>{{account.accname}}</td>
       <td><a href="{{url_for('.modify_account', accno=account.accno)}}">Modify</a></td>
    </tr>

   {% endfor %}

</table>
</div>
</div>

{% endblock %}

btt/templates/add_account.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}BTT{% endblock %}

{% block page_content %}

<h2>Add Account: </h2>
<div class="row">
<div class="col-md-3">
{{ wtf.quick_form(form) }}
</div>
</div>

{% endblock %}

btt/templates/add_category.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}BTT{% endblock %}

{% block page_content %}

<h2>Add Category: </h2>
<div class="row">
<div class="col-md-3">
{{ wtf.quick_form(form) }}
</div>
</div>

{% endblock %}

btt/templates/add_transaction.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}BTT{% endblock %}

{% block page_content %}

<h2>Add Transaction: </h2>
<div class="row">
<div class="col-md-3">
{{ wtf.quick_form(form) }}
</div>
</div>

{% endblock %}

btt/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}BTT{% endblock %}

{% block head %}
{{ super() }}
<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico', v=9) }}" type="image/x-icon">
<link rel="icon" href="{{ url_for('static', filename='favicon.ico', v=9) }}" type="image/x-icon">
<link rel="stylesheet" href="{{url_for('static', filename='sitestyle.css', v=55)}}">
{% endblock %}

{% block navbar %}

<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{url_for('web.home_page')}}">BTT</a>
        </div>
    <div class="collapse navbar-collapse" id="navbar-collapse-1">
        <ul class="nav navbar-nav">
            <li {% if menu == "home" %}class="active"{% endif %}><a href="{{url_for('web.home_page')}}">Home</a></li>

            <li {% if menu == "accounts" %}class="active"{% endif %} class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">Accounts<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{{url_for('web.accounts_page')}}">Search/Modify</a></li>
                        <li><a href="{{url_for('web.add_account')}}">Add</a></li>
                    </ul>
            </li>

            <li {% if menu == "categories" %}class="active"{% endif %} class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">Categories<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{{url_for('web.categories_page')}}">Search/Modify</a></li>
                        <li><a href="{{url_for('web.add_category')}}">Add</a></li>
                    </ul>
            </li>

            <li {% if menu == "transactions" %}class="active"{% endif %} class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">Transactions<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{{url_for('web.search_transactions')}}">Search/Modify</a></li>
                        <li><a href="{{url_for('web.add_transaction')}}">Add</a></li>
                        <li><a href="{{url_for('web.upload_transactions')}}">Upload</a></li>
                    </ul>
            </li>


            <li {% if menu == "reports" %}class="active"{% endif %} class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">Reports
                    <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{{url_for('web.reports_page', report_name="Expenses by Category" )}}">Expenses by Category</a></li>
                        <li><a href="{{url_for('web.reports_page', report_name="Income by Category" )}}">Income by Category</a></li>
                        <li><a href="{{url_for('web.reports_page', report_name="Cash Flow" )}}">Cash Flow</a></li>
                        <li><a href="{{url_for('web.reports_page', report_name="Account Balances" )}}">Account Balances</a></li>
                    </ul>
            </li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
            {% if current_user.is_authenticated %}
            <li {% if menu == "myaccount" %}class="active"{% endif %} class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    My Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="{{ url_for('auth.change_password') }}">Change Password</a></li>
                    <li><a href="{{ url_for('auth.change_email_request') }}">Change Email</a></li>
                    <li><a href="{{ url_for('auth.change_group') }}">Change Group</a></li>
                    <li><a href="{{ url_for('auth.delete_user') }}">Delete My Account</a></li>
                    <li><a href="{{ url_for('auth.logout') }}">Log Out</a></li>
                </ul>
            </li>
            {% else %}
            <li><a href="{{ url_for('auth.login') }}">Log In</a></li>
            {% endif %}
        </ul>

    </div>

    </div>

</nav>

{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="top-buffer">
        {% for message in get_flashed_messages() %}
        <div class="alert alert-warning">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ message }}
        </div>
        {% endfor %}

        {% block page_content %}{% endblock %}
    </div>
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
{{ moment.include_moment() }}
{% endblock %}

btt/templates/header.html
<!DOCTYPE html>
<html lang="en">
<head>
   <!-- Set width of the page to width of device screen and set initial zoom level -->
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
   <!-- Enable style sheet -->
   <link rel="stylesheet" title="Site Style" href="/static/style.css" type="text/css"/>
   <!-- jQuery -->
   <script src="jquery-3.1.0.min.js"></script>
   <script src="jquery-funcs.js"></script>
   <!-- Set title for browser toolbar etc -->
   <title>PFT</title>
</head>
<body>
   <!-- Heading banner with logo, text and buttons -->
   <header>
      <h1>
         <img class="logo" src="/static/logo.png" width="30" height="28" alt="$"/>
         Bank Transaction Tracker
         <a href="/logout"><button class="banner">Log Out</button></a>
<!--
        Put something here to indicate which user is logged in and any demo account restrictions.
-->
      </h1>
   </header>

<!-- Navigation menu -->
<div class="row">
<nav>
<ul class="menu">
    <li class="col-1"><a {% if menu == "home" %} class="active" {% endif %} href="/home">Home</a></li>
    <li class="col-1"><a {% if menu == "accounts" %} class="active" {% endif %} href="/accounts">Accounts</a></li>
    <li class="col-1"><a {% if menu == "transactions" %} class="active" {% endif %} href="/transactions">Transactions</a></li>
    <li class="col-1"><a {% if menu == "categories" %} class="active" {% endif %} href="/categories">Categories</a></li>
    <li class="col-1"><a {% if menu == "reports" %} class="active" {% endif %} href="/reports">Reports</a></li>
</ul>
</nav>
</div>

btt/templates/home.html
{% extends "base.html" %}

{% block title %}BTT{% endblock %}

{% block page_content %}

<h2>Welcome to Bank Transaction Tracker (BTT)</h2>
    {% if current_user.is_authenticated %}
        <div class="row">
        <div class="col-md-4">
        <table class="table table-striped table-bordered table-hover">
            <tr>
               <td>You are logged in as:</td>
               <td>{{ current_user.email }}</td>
            </tr>
            <tr>
                <td>Your current group is:</td>
                <td>{{ current_user.group().name }}</td>
            </tr>
            <tr>
              <td>Login time:</td>
              <td>{{ moment(login_time).format('MMMM Do YYYY, h:mm a') }}</td>
            </tr>
            <tr>
               <td>You logged in:</td>
               <td>{{ moment(login_time).fromNow(refresh=True) }}</td>
            </tr>
        </table>
    {% else %}
        <p>Bank Transaction Tracker (BTT) is an application for tracking income and expenditure.</p>
        <p>To login or register, <a href="{{ url_for('auth.login') }}">please click here.</a></p>
    {% endif %}
        </div>
        </div>
{% endblock %}

btt/templates/modify_account.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}BTT{% endblock %}

{% block page_content %}

<h2>Modify Account: </h2>
<div class="row">
<div class="col-md-3">
{{ wtf.quick_form(form) }}
</div>
</div>

{% endblock %}

btt/templates/modify_category.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}BTT{% endblock %}

{% block page_content %}

<h2>Modify Category: </h2>
<div class="row">
<div class="col-md-3">
{{ wtf.quick_form(form) }}
</div>
</div>

{% endblock %}

btt/templates/modify_transaction.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}BTT{% endblock %}

{% block page_content %}

<h2>Modify Transaction: </h2>
<div class="row">
<div class="col-md-3">
{{ wtf.quick_form(form) }}
</div>
</div>

{% endblock %}

btt/templates/process_transactions.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}BTT{% endblock %}

{% block page_content %}

<h2>Process Uploaded Transactions: </h2>
<form class="form form-horizontal" method="post" role="form" enctype="multipart/form-data">
  {{ form.hidden_tag() }}
  {{ wtf.form_errors(form, hiddens="only") }}

  <div class="col-md-12">
  {{ wtf.form_field(form.add) }}
  {{ wtf.form_field(form.cancel) }}
  {{ wtf.form_field(form.date_format) }}
  </div>

  <table class="table table-striped table-bordered table-hover">

  <tr>
  {% for classification in form.col_classifications %}
      <th><div class="col-xs-12">{{ wtf.form_field(classification.form.column_label) }}</div></th>
  {% endfor %}
  <th>Category</th>
  <th>Action</th>
  </tr>


 {% for transno in range(num_transactions) %}

  <tr>
      {% for field in transactions[transno] %}
      <td>{{ field }}</td>
      {% endfor %}
      <td><div class="col-xs-12">{{ wtf.form_field(form.row_classifications[transno].form.category_name)}}</div></td>
      <td><div class="col-xs-12">{{ wtf.form_field(form.row_classifications[transno].form.action)}}</div></td>
  </tr>

 {% endfor %}

  </table>

  <div class="col-md-12">
  {{ wtf.form_field(form.add) }}
  {{ wtf.form_field(form.cancel) }}
  </div>

</form>

{% endblock %}

btt/templates/reports.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block title %}
  BTT
{% endblock %}

{% block head %}
  {{ super() }}
  <script src="https://cdn.bokeh.org/bokeh/release/bokeh-3.3.0.min.js"></script>
  <script src="https://cdn.bokeh.org/bokeh/release/bokeh-widgets-3.3.0.min.js"></script>

  {{ graph[0]|safe }}
{% endblock %}

{% block page_content %}
  <h2>{{ report_name }}:</h2>

  <div class="row">
    <div class="col-md-5 nopadding">{{ graph[1]|safe }}</div>

    <div class="col-md-3">
      <form class="form form-horizontal" method="post" role="form" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        {{ wtf.form_errors(form, hiddens = 'only') }}

        {{ wtf.form_field(form.start_date) }}

        {{ wtf.form_field(form.end_date) }}

        {% if report_name == 'Account Balances' %}
          {{ wtf.form_field(form.account_name) }}
        {% else %}
          <div class="hidden">{{ wtf.form_field(form.account_name) }}</div>
        {% endif %}

        {{ wtf.form_field(form.refresh) }}
      </form>
    </div>

    {% if graph[2] %}
      <div class="col-md-3">
        <h4>Full Details:</h4>
        <table class="table table-striped table-bordered table-hover">
          <tr>
            <th>Expense</th>
            <th>Percentage</th>
          </tr>
          {% for item in graph[2] %}
            <tr>
              <td>{{ item[0] }}</td>
              <td>{{ item[1] }}</td>
            </tr>
          {% endfor %}
        </table>
      </div>
    {% endif %}
  </div>
{% endblock %}

btt/templates/transactions.html
{% extends "base.html" %}

{% block title %}BTT{% endblock %}

{% block page_content %}

<h2>Transactions:</h2>


<table class="table table-striped table-bordered table-hover">
    <tr>
        <th>Date</th>
        <th>Description</th>
        <th>Category</th>
        <th>Type</th>
        <th>Account</th>
        <th class="text-center">Amount</th>
        <th>Action</th>
        <th>Action</th>
    </tr>

   {% for transaction in transactions %}

   <tr>
       <td>{{transaction.date}}</td>
       <td>{{transaction.description}}</td>
       <td>{{transaction.category.catname}}</td>
       <td>{{transaction.category.cattype}}</td>
       <td>{{transaction.account.accname}}</td>
       <td class="text-right">{{'{:,.2f}'.format(transaction.amount / 100.0)}}</td>
       <td><a href="{{url_for('.modify_transaction', transno=transaction.transno)}}">Modify</a></td>
       <td><a href="{{url_for('.delete_transaction', transno=transaction.transno)}}">Delete</a></td>
   </tr>

   {% endfor %}

</table>

{% endblock %}

btt/templates/upload_transactions.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}BTT{% endblock %}

{% block page_content %}

<h2>Upload Transactions: </h2>
<div class="row">
<div class="col-md-3">
<form class="form form-horizontal" method="post" role="form" enctype="multipart/form-data">
  {{ form.hidden_tag() }}
  {{ wtf.form_errors(form, hiddens="only") }}

  <div class="col-md-12">
  {{ wtf.form_field(form.transactions_file)}}
  </div>

  <div class="col-md-12">
  {{ wtf.form_field(form.account)}}
  </div>

  <div class="col-md-12">
  {{ wtf.form_field(form.upload) }}
  <a href="{{url_for('.transactions_page')}}"><button type="button" class="btn btn-default">Cancel</button></a>
  </div>

</form>
</div>
</div>

{% endblock %}